trigger:
  branches:
    include:
      - main
      - master
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 9 SDK'
    inputs:
      packageType: 'sdk'
      version: '9.x'
      includePreviewVersions: true

  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'Build solution'

  - script: dotnet test --configuration $(buildConfiguration) --no-build --logger trx --results-directory $(Agent.TempDirectory)
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(Agent.TempDirectory)'

  - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish application'

  - task: ArchiveFiles@2
    displayName: 'Create artifact'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/DemoCLI.zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/DemoCLI.zip'
      artifactName: 'drop'